### ISSUE TITLE
[BUG] Tokens for font sizes are not being create as rem values.

### ISSUE THREAD

**Issue by mariannuar** [emulsify-ds/emulsify-ui-kit#103]
**Describe the bug**
When creating tokens, font sizes are being created as `px` values instead of `rem` values. However, the values is coming without the `px` word, only the value itself. So when using tokens for font sizes, the sizes of the fonts are not changing.

**To Reproduce**
1. Run `npm run develop`
2. Go to http://localhost:6006/?path=/story/components-button--button
3. Open the inspector and inspect the font size of any `Button text`
4. Scroll down to the styles tab/section in the inspector
5. You can see that the button text is using the `--font-size-body`, and this value is coming as `18` instead of `18px` or `1.125rem`.

**Expected behavior**
Font sizes tokens should be coming in this way `18px` or the `rem` value, instead of only `18`. It would be better if the value comes as they were coming before, in `rem` values.

**Screenshots**
<img width="758" alt="Captura de pantalla 2023-08-20 a la(s) 12 20 55 a m" src="https://github.com/emulsify-ds/emulsify-ui-kit/assets/48533432/dfea0360-b956-418d-9ba6-540a82f0ca32">

**Comment by amazingrando** [comment]
This may relate to #102.
