### ISSUE TITLE
Use unitless values for line-heights

### ISSUE THREAD

**Issue by ModulesUnraveled** [emulsify-ds/emulsify-ui-kit#30]
**Problem description:**
We should use unitless values for line-height, not percentages.

> A unitless value is passed to the child element and its line height is calculated using the child's font size, whereas a percentage or em value will cause a line height to be calculated for the parent, and then that calculated value is passed to the child.

**Suggested solution:**
Update the tokens from percentages like 150% to unitless values like 1.5.

**Comment by amazingrando** [comment]
@ModulesUnraveled This will have to be resolved by converting the percentage values into unitless values in Style Dictionary because Figma doesn't accept unitless values. Fortunately, unitless values map well to percentages, with 120% mapping to 1.2.
