### ISSUE TITLE
Status Alerts styled with design tokens

### ISSUE THREAD

**Issue by amazingrando** [emulsify-ds/emulsify-ui-kit#68]
Status alerts are the special notices that alert the user to timely information they may need. Below is an example of status alerts for the Yale Cybersecurity site.

Bring the [Compound Status component ](https://github.com/emulsify-ds/emulsify-ui-kit/tree/main/compound/02-molecules/status)into the UI kit.

Use the [defined status tokens](https://github.com/emulsify-ds/emulsify-ui-kit/blob/aee892c0fdc7e92cbb6dd910bde4bb220d84f9ae/src/components/tokens/_tokens.scss#L67-L76) in the CSS for this component.

![Image](https://github.com/emulsify-ds/emulsify-ui-kit/assets/409903/658424e6-1959-44dd-b256-f5f38d4c194f)

**Comment by mndonx** [comment]
@amazingrando I have a PR ready to go for this one too -- though I want to double check what is coming from Figma because I don't think the contrast is correct.

**Comment by mndonx** [comment]
I found there were Status color tokens in there already. However, they may need updating as the text colors don't always pass contrast tests.
