### ISSUE TITLE
Logo component

### ISSUE THREAD

**Issue by amazingrando** [emulsify-ds/emulsify-ui-kit#95]
Migrated the [Logo component from Compound](https://github.com/emulsify-ds/emulsify-ui-kit/tree/main/compound/02-molecules/logo) into the UI kit.

There are no associated design tokens with this component.

**Comment by mndonx** [comment]
@amazingrando I have a PR for this, but I just need correct access rights to push to the repo.

**Comment by amazingrando** [comment]
@mndonx I've added you to the repo as a maintainer.
